name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  macos:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script
        run: |
          ./setup.sh

  ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script
        run: |
          ./setup.sh
